### ISSUE TITLE
kewl css

### ISSUE THREAD

**Issue by k-tten** [VoncheyK/Catyy.ga#1]
```css
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap");

body {
  background-color: rgb(27, 27, 27);
  font-family: "Open Sans", sans-serif;
}

.container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  padding: 8px;
  margin: 4px;
}

.top {
  text-align: center;
  font-weight: 100;
  color: white;
  letter-spacing: 4px;
  font-size: 48px;
  user-select: none;
}

.btns {
  text-align: center;
  width: 128px;
  margin: 0 auto;
  border: 1px solid rgb(0, 255, 255);
  color: rgb(0, 255, 255);
  border-radius: 3px;
  padding: 8px;
  transition: 0.2s all ease;
  cursor: pointer;
}

.inv {
  font-size: 20px;
  text-decoration: none;
  color: inherit;
}

.btns:hover {
  color: rgb(27, 27, 27);
  background-color: rgb(0, 255, 255);
  border: 1px solid rgb(27, 27, 27);
}
```
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="title" content=" Catyy / Home" />
    <meta name="author" content="VoncheyK" />
    <meta name="description" content="Welcome to the Home page of Catyy!" />
    <title>Catyy | Home</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <div class="container">
      <h1 class="top">Catyy..</h1>
      <div class="btns">
        <a
          class="inv"
          target="blank"
          href="https://discord.com/api/oauth2/authorize?client_id=725047440465461268&permissions=0&scope=bot"
          >Invite The Bot</a
        >
      </div>
    </div>
  </body>
</html>
```
here you go
